name: Publish Fotoobo distributions 📦 to PyPI

on: push

jobs:
  build-n-publish-to-pypi:
    if: startsWith(github.ref, 'refs/tags')
    name: Build and publish Fotoobo distributions 📦 to PyPI
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Set up Python 3.10
        uses: actions/setup-python@v3
        with:
          python-version: "3.10"
      - name: Install poetry
        run: pip install poetry
      - name: Use TEST-PYPI
        run: poetry config repositories.test-pypi https://test.pypi.org/legacy/
      - name: Configure API token for TEST-PYPI
        run: poetry config pypi-token.test-pypi "${{ secrets.PYPI_API_TOKEN }}"
      - name: Configure API token
        run: poetry config pypi-token.pypi "${{ secrets.PYPI_API_TOKEN }}"
      - name: Build and then publish Fotoobo to PyPI
        run: poetry publish --build -r test-pypi
